/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BackLink: typeof import('./src/components/BackLink.vue')['default']
    ErrorState: typeof import('./src/components/ErrorState.vue')['default']
    LoadingSpinner: typeof import('./src/components/LoadingSpinner.vue')['default']
    PageHeader: typeof import('./src/components/PageHeader.vue')['default']
    PublicLayout: typeof import('./src/components/PublicLayout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StepIndicator: typeof import('./src/components/StepIndicator.vue')['default']
  }
}
