/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    EmptyState: typeof import('./src/components/shared/EmptyState.vue')['default']
    ErrorState: typeof import('./src/components/shared/ErrorState.vue')['default']
    LoadingSpinner: typeof import('./src/components/shared/LoadingSpinner.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatusBadge: typeof import('./src/components/shared/StatusBadge.vue')['default']
    StepProgress: typeof import('./src/components/shared/StepProgress.vue')['default']
  }
}
